name: Test

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install luarocks
        run: sudo apt-get install luarocks lua-check
      - name: Install luaunit
        run: sudo luarocks install luaunit
      - name: Run tests
        run: lua Tests/Test.lua
      - name: Lint
        run: luacheck .
